# Generated by Django 3.2.7 on 2021-11-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20211127_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='comics',
            field=models.ManyToManyField(to='main_app.Comic'),
        ),
    ]
